#!/bin/bash

# This file is supposed to be run in the root folder
# Had trobule with the makefile so added this separate
# bash script to create the test executables.

# Make variable names for the test file
#TEST_FILE="benchmark/matrix_mult_benchmark.c"
TEST_FILE="tests/verifications/matrix_mult_single_verification.c"
OUTPUT_FILE="program"

# Clean and make a new build using make
make clean
make

# Remove the my_test
rm $OUTPUT_FILE

# Manually make the test file
gcc -O3 -mavx -march=native -funroll-loops -fopenmp -c $TEST_FILE -o build/$(basename $TEST_FILE .c).o

# Create a binary file consisting of the test file
gcc -g $(find ./build -name "*.o") -o $OUTPUT_FILE -lopenblas
chmod +x $OUTPUT_FILE
