#!/bin/bash

# This file is supposed to be run in the root folder
# Had trobule with the makefile so added this separate
# bash script to create the test executables.

# Make variable names for the test file
TEST_FILE="tests/matrix_mult_multi_profiling.c"
OUTPUT_FILE="test"

# Clean and make a new build using make
make clean
make

# Remove the my_test
rm $OUTPUT_FILE

# Manually make the test file
gcc -O3 -mavx -march=native -fopt-info-vec -ffast-math -funroll-loops -fopenmp -c $TEST_FILE -o build/$(basename $TEST_FILE .c).o

# Create a binary file consisting of the test file
gcc -g $(find ./build -name "*.o") -o $OUTPUT_FILE -lopenblas
chmod +x $OUTPUT_FILE

# Run the test file
./test
